In [126]:
import pandas as pd

In [127]:
xlsLocalidadesIBGE = pd.ExcelFile('BR_Localidades_2010_v1.xlsx')

In [128]:
dfLocalidades = xlsLocalidadesIBGE.parse('BR_Localidades_2010_v1')

In [129]:
dfLocalidades.head()

,GM_PONTO,ID,CD_GEOCODIGO,TIPO,CD_GEOCODBA,NM_BAIRRO,CD_GEOCODSD,NM_SUBDISTRITO,CD_GEOCODDS,NM_DISTRITO,...,NM_MESO,NM_UF,CD_NIVEL,CD_CATEGORIA,NM_CATEGORIA,NM_LOCALIDADE,LONG,LAT,ALT,GM_PONTO_sk
0,NaN,1,110001505000001,URBANO,1.100015e+11,Redondo,11000150500,NaN,110001505,ALTA FLORESTA D'OESTE,...,LESTE RONDONIENSE,RONDÔNIA,1,5,CIDADE,ALTA FLORESTA D'OESTE,-61.999824,-11.935540,337.735719,1J6+^YP=gnhf
1,NaN,2,110001515000001,URBANO,NaN,NaN,11000151500,NaN,110001515,FILADÉLFIA D'OESTE,...,LESTE RONDONIENSE,RONDÔNIA,2,15,VILA,FILADÉLFIA D'OESTE,-62.043898,-12.437239,215.244429,1J6+gStX@d?>
2,NaN,3,110001520000001,URBANO,NaN,NaN,11000152000,NaN,110001520,IZIDOLÂNDIA,...,LESTE RONDONIENSE,RONDÔNIA,2,20,VILA,IZIDOLÂNDIA,-62.175549,-12.601415,181.044807,1J6+gwlc:Gtp
3,NaN,4,110001525000001,URBANO,NaN,NaN,11000152500,NaN,110001525,NOVA GEASE D'OESTE,...,LESTE RONDONIENSE,RONDÔNIA,2,25,VILA,NOVA GEASE D'OESTE,-62.318650,-11.919792,191.576571,1J6+^nhO?byf
4,NaN,5,110001530000001,URBANO,NaN,NaN,11000153000,NaN,110001530,ROLIM DE MOURA DO GUAPORÉ,...,LESTE RONDONIENSE,RONDÔNIA,2,30,VILA,ROLIM DE MOURA DO GUAPORÉ,-62.276812,-13.079806,157.285277,1J6+Hn4dy6Y-

In [130]:
dfLocalidades = dfLocalidades[dfLocalidades.CD_CATEGORIA == 5]

In [132]:
dfLocalidades = dfLocalidades[['NM_LOCALIDADE', 'LAT', 'LONG', 'ALT']].copy()

In [133]:
dfLocalidades.head()

                 NM_LOCALIDADE        LAT       LONG         ALT
0        ALTA FLORESTA D'OESTE -11.935540 -61.999824  337.735719
6                    ARIQUEMES  -9.908463 -63.033269  138.688981
7                       CABIXI -13.499763 -60.544314  236.063160
9                       CACOAL -11.433865 -61.442944  177.453547
13  ALDEIA INDÍGENA - LINHA 12 -11.220610 -61.248991  205.526414

In [173]:
df_01 = pd.read_csv("01_2018.csv", encoding="ISO-8859-1", sep=";")

In [174]:
df_01['data'] = pd.to_datetime('01-01-2018')

In [175]:
df_02 = pd.read_csv("02_2018.csv", encoding="ISO-8859-1", sep=";")

In [176]:
df_02['data'] = pd.to_datetime('01-02-2018')

In [177]:
df_03 = pd.read_csv("03_2018.csv", encoding="ISO-8859-1", sep=";")

In [178]:
df_03['data'] = pd.to_datetime('01-03-2018')

In [179]:
df_04 = pd.read_csv("04_2018.csv", encoding="ISO-8859-1", sep=";")

In [180]:
df_04['data'] = pd.to_datetime('01-04-2018')

In [181]:
df_05 = pd.read_csv("05_2018.csv", encoding="ISO-8859-1", sep=";")

In [182]:
df_05['data'] = pd.to_datetime('01-05-2018')

In [183]:
df_06 = pd.read_csv("06_2018.csv", encoding="ISO-8859-1", sep=";")

In [184]:
df_06['data'] = pd.to_datetime('01-06-2018')

In [185]:
df_07 = pd.read_csv("07_2018.csv", encoding="ISO-8859-1", sep=";")

In [186]:
df_07['data'] = pd.to_datetime('01-07-2018')

In [187]:
df_08 = pd.read_csv("08_2018.csv", encoding="ISO-8859-1", sep=";")

In [188]:
df_08['data'] = pd.to_datetime('01-08-2018')

In [189]:
df_09 = pd.read_csv("09_2018.csv", encoding="ISO-8859-1", sep=";")

In [190]:
df_09['data'] = pd.to_datetime('01-09-2018')

In [191]:
df_10 = pd.read_csv("10_2018.csv", encoding="ISO-8859-1", sep=";")

In [192]:
df_10['data'] = pd.to_datetime('01-10-2018')

In [193]:
df_11 = pd.read_csv("11_2018.csv", encoding="ISO-8859-1", sep=";")

In [194]:
df_11['data'] = pd.to_datetime('01-11-2018')

In [195]:
df_12 = pd.read_csv("12_2018.csv", encoding="ISO-8859-1", sep=";")

In [196]:
df_12['data'] = pd.to_datetime('01-12-2018')

In [198]:
frames = [df_01, df_02, df_03, df_04, df_05, df_06, df_07, df_08, df_09, df_10, df_11, df_12]

In [199]:
df = pd.concat(frames)

In [200]:
df.head()

,Município,Internações,AIH_aprovadas,Valor_total,Valor_serviços_hospitalares,Val_serv_hosp_-_compl_federal,Val_serv_hosp_-_compl_gestor,Valor_serviços_profissionais,Val_serv_prof_-_compl_federal,Val_serv_prof_-_compl_gestor,Valor_médio_AIH,Valor_médio_intern,Dias_permanência,Média_permanência,Óbitos,Taxa_mortalidade,data
0,110001 Alta Floresta D'Oeste,1,1,"503,19","477,48",-,-,"25,71",-,-,"503,19","503,19",3,"3,0",-,-,2018-01-01
1,110034 Alvorada D'Oeste,1,1,"479,19","453,48",-,-,"25,71",-,-,"479,19","479,19",2,"2,0",-,-,2018-01-01
2,110002 Ariquemes,1,1,"52,22","41,34",-,-,"10,88",-,-,"52,22","52,22",1,"1,0",-,-,2018-01-01
3,110004 Cacoal,5,5,"2476,95","2348,40",-,-,"128,55",-,-,"495,39","495,39",10,"2,0",-,-,2018-01-01
4,110005 Cerejeiras,3,3,"1453,57","1376,44",-,-,"77,13",-,-,"484,52","484,52",6,"2,0",-,-,2018-01-01

In [201]:
df['NM_LOCALIDADE'] = df['Município'].str[7:].str.upper()

In [202]:
df.head()

,Município,Internações,AIH_aprovadas,Valor_total,Valor_serviços_hospitalares,Val_serv_hosp_-_compl_federal,Val_serv_hosp_-_compl_gestor,Valor_serviços_profissionais,Val_serv_prof_-_compl_federal,Val_serv_prof_-_compl_gestor,Valor_médio_AIH,Valor_médio_intern,Dias_permanência,Média_permanência,Óbitos,Taxa_mortalidade,data,NM_LOCALIDADE
0,110001 Alta Floresta D'Oeste,1,1,"503,19","477,48",-,-,"25,71",-,-,"503,19","503,19",3,"3,0",-,-,2018-01-01,ALTA FLORESTA D'OESTE
1,110034 Alvorada D'Oeste,1,1,"479,19","453,48",-,-,"25,71",-,-,"479,19","479,19",2,"2,0",-,-,2018-01-01,ALVORADA D'OESTE
2,110002 Ariquemes,1,1,"52,22","41,34",-,-,"10,88",-,-,"52,22","52,22",1,"1,0",-,-,2018-01-01,ARIQUEMES
3,110004 Cacoal,5,5,"2476,95","2348,40",-,-,"128,55",-,-,"495,39","495,39",10,"2,0",-,-,2018-01-01,CACOAL
4,110005 Cerejeiras,3,3,"1453,57","1376,44",-,-,"77,13",-,-,"484,52","484,52",6,"2,0",-,-,2018-01-01,CEREJEIRAS

In [203]:
result = pd.merge(df,
                 dfLocalidades[['NM_LOCALIDADE', 'LAT', 'LONG', 'ALT']],
                 on='NM_LOCALIDADE', 
                 how='left')

In [204]:
result.head()

,Município,Internações,AIH_aprovadas,Valor_total,Valor_serviços_hospitalares,Val_serv_hosp_-_compl_federal,Val_serv_hosp_-_compl_gestor,Valor_serviços_profissionais,Val_serv_prof_-_compl_federal,Val_serv_prof_-_compl_gestor,...,Valor_médio_intern,Dias_permanência,Média_permanência,Óbitos,Taxa_mortalidade,data,NM_LOCALIDADE,LAT,LONG,ALT
0,110001 Alta Floresta D'Oeste,1,1,"503,19","477,48",-,-,"25,71",-,-,...,"503,19",3,"3,0",-,-,2018-01-01,ALTA FLORESTA D'OESTE,-11.935540,-61.999824,337.735719
1,110034 Alvorada D'Oeste,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",2,"2,0",-,-,2018-01-01,ALVORADA D'OESTE,-11.344130,-62.277275,182.400130
2,110002 Ariquemes,1,1,"52,22","41,34",-,-,"10,88",-,-,...,"52,22",1,"1,0",-,-,2018-01-01,ARIQUEMES,-9.908463,-63.033269,138.688981
3,110004 Cacoal,5,5,"2476,95","2348,40",-,-,"128,55",-,-,...,"495,39",10,"2,0",-,-,2018-01-01,CACOAL,-11.433865,-61.442944,177.453547
4,110005 Cerejeiras,3,3,"1453,57","1376,44",-,-,"77,13",-,-,...,"484,52",6,"2,0",-,-,2018-01-01,CEREJEIRAS,-13.195033,-60.818426,262.811307

In [205]:
df = result

In [206]:
df.head()

,Município,Internações,AIH_aprovadas,Valor_total,Valor_serviços_hospitalares,Val_serv_hosp_-_compl_federal,Val_serv_hosp_-_compl_gestor,Valor_serviços_profissionais,Val_serv_prof_-_compl_federal,Val_serv_prof_-_compl_gestor,...,Valor_médio_intern,Dias_permanência,Média_permanência,Óbitos,Taxa_mortalidade,data,NM_LOCALIDADE,LAT,LONG,ALT
0,110001 Alta Floresta D'Oeste,1,1,"503,19","477,48",-,-,"25,71",-,-,...,"503,19",3,"3,0",-,-,2018-01-01,ALTA FLORESTA D'OESTE,-11.935540,-61.999824,337.735719
1,110034 Alvorada D'Oeste,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",2,"2,0",-,-,2018-01-01,ALVORADA D'OESTE,-11.344130,-62.277275,182.400130
2,110002 Ariquemes,1,1,"52,22","41,34",-,-,"10,88",-,-,...,"52,22",1,"1,0",-,-,2018-01-01,ARIQUEMES,-9.908463,-63.033269,138.688981
3,110004 Cacoal,5,5,"2476,95","2348,40",-,-,"128,55",-,-,...,"495,39",10,"2,0",-,-,2018-01-01,CACOAL,-11.433865,-61.442944,177.453547
4,110005 Cerejeiras,3,3,"1453,57","1376,44",-,-,"77,13",-,-,...,"484,52",6,"2,0",-,-,2018-01-01,CEREJEIRAS,-13.195033,-60.818426,262.811307

In [207]:
df.dtypes

Município                                object
Internações                               int64
AIH_aprovadas                             int64
Valor_total                              object
Valor_serviços_hospitalares              object
Val_serv_hosp_-_compl_federal            object
Val_serv_hosp_-_compl_gestor             object
Valor_serviços_profissionais             object
Val_serv_prof_-_compl_federal            object
Val_serv_prof_-_compl_gestor             object
Valor_médio_AIH                          object
Valor_médio_intern                       object
Dias_permanência                         object
Média_permanência                        object
Óbitos                                   object
Taxa_mortalidade                         object
data                             datetime64[ns]
NM_LOCALIDADE                            object
LAT                                     float64
LONG                                    float64
ALT                                     float64
dtype: object

In [208]:
df

,Município,Internações,AIH_aprovadas,Valor_total,Valor_serviços_hospitalares,Val_serv_hosp_-_compl_federal,Val_serv_hosp_-_compl_gestor,Valor_serviços_profissionais,Val_serv_prof_-_compl_federal,Val_serv_prof_-_compl_gestor,...,Valor_médio_intern,Dias_permanência,Média_permanência,Óbitos,Taxa_mortalidade,data,NM_LOCALIDADE,LAT,LONG,ALT
0,110001 Alta Floresta D'Oeste,1,1,"503,19","477,48",-,-,"25,71",-,-,...,"503,19",3,"3,0",-,-,2018-01-01,ALTA FLORESTA D'OESTE,-11.935540,-61.999824,337.735719
1,110034 Alvorada D'Oeste,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",2,"2,0",-,-,2018-01-01,ALVORADA D'OESTE,-11.344130,-62.277275,182.400130
2,110002 Ariquemes,1,1,"52,22","41,34",-,-,"10,88",-,-,...,"52,22",1,"1,0",-,-,2018-01-01,ARIQUEMES,-9.908463,-63.033269,138.688981
3,110004 Cacoal,5,5,"2476,95","2348,40",-,-,"128,55",-,-,...,"495,39",10,"2,0",-,-,2018-01-01,CACOAL,-11.433865,-61.442944,177.453547
4,110005 Cerejeiras,3,3,"1453,57","1376,44",-,-,"77,13",-,-,...,"484,52",6,"2,0",-,-,2018-01-01,CEREJEIRAS,-13.195033,-60.818426,262.811307
5,110006 Colorado do Oeste,2,2,"1061,61","957,55",-,-,"104,06",-,-,...,"530,80",8,"4,0",-,-,2018-01-01,COLORADO DO OESTE,-13.130564,-60.555067,419.090613
6,110008 Costa Marques,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",-,-,-,-,2018-01-01,COSTA MARQUES,-12.436014,-64.231654,145.213903
7,110010 Guajará-Mirim,7,7,"3394,33","3214,36",-,-,"179,97",-,-,...,"484,90",18,"2,6",-,-,2018-01-01,GUAJARÁ-MIRIM,-10.773884,-65.323952,133.414381
8,110011 Jaru,2,2,"1006,38","954,96",-,-,"51,42",-,-,...,"503,19",6,"3,0",-,-,2018-01-01,JARU,-10.435949,-62.476231,162.551328
9,110014 Nova Brasilândia D'Oeste,3,3,"1437,57","1360,44",-,-,"77,13",-,-,...,"479,19",11,"3,7",-,-,2018-01-01,NOVA BRASILÂNDIA D'OESTE,-11.721325,-62.308230,259.417475
10,110018 Pimenta Bueno,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",1,"1,0",-,-,2018-01-01,PIMENTA BUENO,-11.677537,-61.183666,186.174033
11,110020 Porto Velho,14,14,"7794,82","7349,75",-,-,"445,07",-,-,...,"556,77",88,"6,3",-,-,2018-01-01,PORTO VELHO,-8.768892,-63.831446,86.895415
12,110028 Rolim de Moura,2,2,"1022,38","970,96",-,-,"51,42",-,-,...,"511,19",9,"4,5",-,-,2018-01-01,ROLIM DE MOURA,-11.722259,-61.785781,226.711103
13,110029 Santa Luzia D'Oeste,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",3,"3,0",-,-,2018-01-01,SANTA LUZIA D'OESTE,-11.908423,-61.773305,265.234157
14,110032 São Miguel do Guaporé,3,3,"1453,57","1376,44",-,-,"77,13",-,-,...,"484,52",3,"1,0",-,-,2018-01-01,SÃO MIGUEL DO GUAPORÉ,-11.699490,-62.720063,191.082628
15,110030 Vilhena,1,1,"495,19","469,48",-,-,"25,71",-,-,...,"495,19",2,"2,0",-,-,2018-01-01,VILHENA,-12.741373,-60.138584,595.093769
16,120033 Mâncio Lima,2,2,"982,38","930,96",-,-,"51,42",-,-,...,"491,19",4,"2,0",-,-,2018-01-01,MÂNCIO LIMA,-7.593223,-72.916501,187.065998
17,120038 Plácido de Castro,2,2,"1030,38","978,96",-,-,"51,42",-,-,...,"515,19",9,"4,5",-,-,2018-01-01,PLÁCIDO DE CASTRO,-10.335133,-67.188260,129.189484
18,120039 Porto Walter,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",2,"2,0",-,-,2018-01-01,PORTO WALTER,-8.266666,-72.742334,201.805961
19,120040 Rio Branco,1,1,"1474,64","1313,33",-,-,"161,31",-,-,...,"1474,64",5,"5,0",-,-,2018-01-01,RIO BRANCO,-9.978299,-67.810529,137.865746
20,120040 Rio Branco,1,1,"1474,64","1313,33",-,-,"161,31",-,-,...,"1474,64",5,"5,0",-,-,2018-01-01,RIO BRANCO,-15.235683,-58.117939,187.085274
21,130010 Anori,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",3,"3,0",-,-,2018-01-01,ANORI,-3.745386,-61.658955,20.346246
22,130090 Canutama,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",3,"3,0",-,-,2018-01-01,CANUTAMA,-6.529106,-64.394231,52.008963
23,130120 Coari,3,3,"1509,57","1432,44",-,-,"77,13",-,-,...,"503,19",9,"3,0",-,-,2018-01-01,COARI,-4.084219,-63.142184,37.939947
24,130140 Eirunepé,2,2,"966,38","914,96",-,-,"51,42",-,-,...,"483,19",10,"5,0",-,-,2018-01-01,EIRUNEPÉ,-6.667353,-69.866290,122.174399
25,130180 Ipixuna,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",3,"3,0",-,-,2018-01-01,IPIXUNA,-7.050980,-71.694418,156.327962
26,130255 Manaquiri,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",3,"3,0",-,-,2018-01-01,MANAQUIRI,-3.429080,-60.458881,29.481121
27,130260 Manaus,44,44,"23396,65","22174,17",-,-,"1222,48",-,-,...,"531,74",116,"2,6",-,-,2018-01-01,MANAUS,-3.134691,-60.023335,34.356331
28,130290 Maués,2,2,"974,38","922,96",-,-,"51,42",-,-,...,"487,19",3,"1,5",-,-,2018-01-01,MAUÉS,-3.386428,-57.715034,24.058942
29,130340 Parintins,2,2,"958,38","906,96",-,-,"51,42",-,-,...,"479,19",6,"3,0",-,-,2018-01-01,PARINTINS,-2.627053,-56.736292,17.327756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17695,520860 Goianésia,3,3,"1209,51","1131,58",-,-,"77,93",-,-,...,"403,17",8,"2,7",-,-,2018-01-12,GOIANÉSIA,-15.322289,-49.115810,627.178622
17696,520870 Goiânia,25,25,"41087,00","36637,84",-,-,"4449,16",-,-,...,"1643,48",122,"4,9",4,"16,00",2018-01-12,GOIÂNIA,-16.673310,-49.255814,753.922667
17697,520960 Heitoraí,8,8,"3936,75","3678,43",-,-,"258,32",-,-,...,"492,09",24,"3,0",-,-,2018-01-12,HEITORAÍ,-15.720216,-49.829340,657.521791
17698,520970 Hidrolândia,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",2,"2,0",-,-,2018-01-12,HIDROLÂNDIA,-4.407999,-40.401817,190.434359
17699,520970 Hidrolândia,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",2,"2,0",-,-,2018-01-12,HIDROLÂNDIA,-16.960945,-49.229784,822.750260
17700,521000 Inhumas,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",1,"1,0",-,-,2018-01-12,INHUMAS,-16.359960,-49.500225,785.702034
17701,521120 Itapuranga,3,3,"1437,57","1360,44",-,-,"77,13",-,-,...,"479,19",6,"2,0",-,-,2018-01-12,ITAPURANGA,-15.562331,-49.944493,646.515276
17702,521130 Itarumã,1,1,"52,22","41,34",-,-,"10,88",-,-,...,"52,22",-,-,-,-,2018-01-12,ITARUMÃ,-18.761660,-51.348890,501.015837
17703,521150 Itumbiara,9,9,"4614,31","4382,92",-,-,"231,39",-,-,...,"512,70",32,"3,6",1,"11,11",2018-01-12,ITUMBIARA,-18.417682,-49.220870,461.810283
17704,521390 Mossâmedes,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",2,"2,0",-,-,2018-01-12,MOSSÂMEDES,-16.119654,-50.218050,622.431271
17705,521400 Mozarlândia,2,2,"958,38","906,96",-,-,"51,42",-,-,...,"479,19",4,"2,0",-,-,2018-01-12,MOZARLÂNDIA,-14.747589,-50.570214,306.243200
17706,521460 Niquelândia,2,2,"998,38","946,96",-,-,"51,42",-,-,...,"499,19",6,"3,0",-,-,2018-01-12,NIQUELÂNDIA,-14.469110,-48.458585,578.343255
17707,521483 Nova Crixás,17,17,"8146,23","7709,16",-,-,"437,07",-,-,...,"479,19",35,"2,1",-,-,2018-01-12,NOVA CRIXÁS,-14.095611,-50.342000,292.599456
17708,521520 Novo Brasil,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",1,"1,0",-,-,2018-01-12,NOVO BRASIL,-16.032671,-50.716314,381.752936
17709,521530 Orizona,12,12,"5750,28","5441,76",-,-,"308,52",-,-,...,"479,19",26,"2,2",-,-,2018-01-12,ORIZONA,-17.034766,-48.302148,830.547567
17710,521680 Petrolina de Goiás,9,9,"4312,71","4081,32",-,-,"231,39",-,-,...,"479,19",28,"3,1",-,-,2018-01-12,PETROLINA DE GOIÁS,-16.097418,-49.338798,732.783858
17711,521730 Pirenópolis,4,4,"2012,76","1909,92",-,-,"102,84",-,-,...,"503,19",16,"4,0",-,-,2018-01-12,PIRENÓPOLIS,-15.853342,-48.962527,772.834303
17712,521770 Pontalina,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",2,"2,0",-,-,2018-01-12,PONTALINA,-17.514984,-49.448181,655.656816
17713,521800 Porangatu,1,1,"495,19","469,48",-,-,"25,71",-,-,...,"495,19",2,"2,0",-,-,2018-01-12,PORANGATU,-13.442186,-49.146226,405.450135
17714,521830 Posse,2,2,"990,38","938,96",-,-,"51,42",-,-,...,"495,19",4,"2,0",-,-,2018-01-12,POSSE,-14.087734,-46.362010,834.231601
17715,521850 Quirinópolis,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",2,"2,0",-,-,2018-01-12,QUIRINÓPOLIS,-18.451507,-50.452263,531.957383
17716,521890 Rubiataba,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",2,"2,0",-,-,2018-01-12,RUBIATABA,-15.164313,-49.803410,638.251354
17717,521920 Santa Cruz de Goiás,2,2,"958,38","906,96",-,-,"51,42",-,-,...,"479,19",6,"3,0",-,-,2018-01-12,SANTA CRUZ DE GOIÁS,-17.321553,-48.476690,764.880456
17718,522020 São Miguel do Araguaia,2,2,"982,38","930,96",-,-,"51,42",-,-,...,"491,19",3,"1,5",-,-,2018-01-12,SÃO MIGUEL DO ARAGUAIA,-13.276024,-50.163838,328.854052
17719,522026 São Miguel do Passa Quatro,1,1,"479,19","453,48",-,-,"25,71",-,-,...,"479,19",2,"2,0",-,-,2018-01-12,SÃO MIGUEL DO PASSA QUATRO,-17.050934,-48.664718,853.699984
17720,522060 Silvânia,2,2,"958,38","906,96",-,-,"51,42",-,-,...,"479,19",4,"2,0",-,-,2018-01-12,SILVÂNIA,-16.664617,-48.610570,920.078087
17721,522100 Taquaral de Goiás,1,1,"495,19","469,48",-,-,"25,71",-,-,...,"495,19",2,"2,0",-,-,2018-01-12,TAQUARAL DE GOIÁS,-16.050019,-49.602219,753.140529
17722,522160 Uruaçu,2,2,"958,38","906,96",-,-,"51,42",-,-,...,"479,19",4,"2,0",-,-,2018-01-12,URUAÇU,-14.520220,-49.147486,515.391422
17723,522200 Vianópolis,5,5,"2395,95","2267,40",-,-,"128,55",-,-,...,"479,19",12,"2,4",-,-,2018-01-12,VIANÓPOLIS,-16.742081,-48.513471,1003.087040
17724,530010 Brasília,226,226,"135169,38","127558,14",-,-,"7611,24",-,-,...,"598,09",742,"3,3",1,"0,44",2018-01-12,BRASÍLIA,-15.794087,-47.887905,1115.248357

In [209]:
df['Valor_total'] = df['Valor_total'].str.replace(',','.')

In [210]:
df['Valor_serviços_hospitalares'] = df['Valor_serviços_hospitalares'].str.replace(',','.')

In [211]:
df['Val_serv_hosp_-_compl_federal'] = df['Val_serv_hosp_-_compl_federal'].str.replace(',','.')

In [212]:
df['Val_serv_hosp_-_compl_gestor'] = df['Val_serv_hosp_-_compl_gestor'].str.replace(',','.')

In [213]:
df['Valor_serviços_profissionais'] = df['Valor_serviços_profissionais'].str.replace(',','.')

In [214]:
df['Val_serv_prof_-_compl_federal'] = df['Val_serv_prof_-_compl_federal'].str.replace(',','.')

In [215]:
df['Val_serv_prof_-_compl_gestor'] = df['Val_serv_prof_-_compl_gestor'].str.replace(',','.')

In [216]:
df['Valor_médio_AIH'] = df['Valor_médio_AIH'].str.replace(',','.')

In [217]:
df['Valor_médio_intern'] = df['Valor_médio_intern'].str.replace(',','.')

In [218]:
df['Taxa_mortalidade'] = df['Taxa_mortalidade'].str.replace(',','.')

In [219]:
df['Dias_permanência'] = df['Dias_permanência'].str.replace(',','.')

In [220]:
df['Média_permanência'] = df['Média_permanência'].str.replace(',','.')

In [221]:
df['Óbitos'] = df['Óbitos'].str.replace(',','.')

In [222]:
cols = ['Valor_total', 'Valor_serviços_hospitalares', 
        'Val_serv_hosp_-_compl_federal', 'Val_serv_hosp_-_compl_gestor', 
       'Valor_serviços_profissionais','Val_serv_prof_-_compl_federal', 'Val_serv_prof_-_compl_gestor', 
       'Valor_médio_AIH', 'Valor_médio_intern', 'Taxa_mortalidade', 'Dias_permanência', 'Média_permanência', 'Óbitos'] 
for col in cols:  
    df[col] = df[col].replace('-','0')
    df[col] = pd.to_numeric(df[col])

In [223]:
df.dtypes

Município                                object
Internações                               int64
AIH_aprovadas                             int64
Valor_total                             float64
Valor_serviços_hospitalares             float64
Val_serv_hosp_-_compl_federal           float64
Val_serv_hosp_-_compl_gestor            float64
Valor_serviços_profissionais            float64
Val_serv_prof_-_compl_federal           float64
Val_serv_prof_-_compl_gestor              int64
Valor_médio_AIH                         float64
Valor_médio_intern                      float64
Dias_permanência                          int64
Média_permanência                       float64
Óbitos                                    int64
Taxa_mortalidade                        float64
data                             datetime64[ns]
NM_LOCALIDADE                            object
LAT                                     float64
LONG                                    float64
ALT                                     float64
dtype: object

In [224]:
df.to_csv('final.csv', sep=",")